"""add orders, user_virtual_networks, tariffs, countries tables

Revision ID: 904587f57543
Revises: f940dde41d8d
Create Date: 2025-02-14 15:49:50.936192

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "904587f57543"
down_revision: Union[str, None] = "f940dde41d8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


billing_period_enum = postgresql.ENUM("day", "month", "year", name="billing_period")
price_currency_enum = postgresql.ENUM("dollars", "euro", "ruble", name="price_currency")
status_user_virtual_networks_enum = postgresql.ENUM(
    "active", "inactive", name="status_user_virtual_networks"
)
type_user_virtual_networks_enum = postgresql.ENUM(
    "vmess",
    "vless",
    "trojan",
    "shadowsocks",
    name="type_user_virtual_networks",
)
currency_enum = postgresql.ENUM("dollars", "euro", "ruble", name="currency")
order_status_enum = postgresql.ENUM(
    "completed",
    "failed",
    "in_progress",
    "start",
    name="order_status",
)
order_type_enum = postgresql.ENUM(
    "buy", "refill_traffic", "refill_expire", name="order_type"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "countries",
        sa.Column("view_country", sa.String(length=255), nullable=False),
        sa.Column("key_country", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_country"),
    )
    op.create_table(
        "tariffs",
        sa.Column("view_price", sa.String(length=255), nullable=False),
        sa.Column("term", sa.Integer(), nullable=False, comment="Количество времени"),
        sa.Column(
            "billing_period",
            billing_period_enum,
            nullable=False,
            comment="Период времени",
        ),
        sa.Column("price", sa.Integer(), nullable=False, comment="Цена"),
        sa.Column(
            "currency",
            price_currency_enum,
            nullable=False,
            comment="Валюта",
        ),
        sa.Column(
            "tariff_key",
            sa.String(length=255),
            nullable=True,
            comment="Ключ для тарифа",
        ),
        sa.Column(
            "traffic_limit",
            sa.Integer(),
            server_default="200",
            nullable=False,
            comment="Объем разрешённого трафика",
        ),
        sa.Column("country_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="Статус тарифа"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["countries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tariff_key"),
    )
    op.create_table(
        "user_virtual_networks",
        sa.Column("virtual_network_key", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            status_user_virtual_networks_enum,
            nullable=False,
            comment="Состояние купленного виртуальной сети",
        ),
        sa.Column(
            "type_virtual_networks",
            type_user_virtual_networks_enum,
            nullable=False,
            comment="Тип виртуальной сети",
        ),
        sa.Column("virtual_networks", sa.Text(), nullable=False),
        sa.Column("expire", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "traffic_limit",
            sa.Integer(),
            server_default="200",
            nullable=False,
            comment="Объем разрешённого трафика",
        ),
        sa.Column(
            "tg_used_traffic",
            sa.Integer(),
            nullable=False,
            comment="Сколько гб пользователь уже израсходовал",
        ),
        sa.Column("tg_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "notified_low_traffic_data",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "notified_traffic_data_done",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "notified_expired_soon",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "notified_expired_done",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tg_user_id"],
            ["tg_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("virtual_network_key"),
    )
    op.create_table(
        "orders",
        sa.Column("virtual_network_key", sa.String(length=255), nullable=True),
        sa.Column("tariff_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False, comment="Сумма"),
        sa.Column("tg_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "currency",
            currency_enum,
            nullable=False,
            comment="Валюта",
        ),
        sa.Column(
            "status",
            order_status_enum,
            nullable=False,
            comment="Статус заказа",
        ),
        sa.Column(
            "type",
            order_type_enum,
            nullable=False,
            comment="Тип заказа",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tariff_id"],
            ["tariffs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tg_user_id"],
            ["tg_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders")
    op.drop_table("user_virtual_networks")
    op.drop_table("tariffs")
    op.drop_table("countries")
    billing_period_enum.drop(op.get_bind(), checkfirst=False)
    price_currency_enum.drop(op.get_bind(), checkfirst=False)
    status_user_virtual_networks_enum.drop(op.get_bind(), checkfirst=False)
    type_user_virtual_networks_enum.drop(op.get_bind(), checkfirst=False)
    currency_enum.drop(op.get_bind(), checkfirst=False)
    order_status_enum.drop(op.get_bind(), checkfirst=False)
    order_type_enum.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
