"""add approve, tg_id_approve field in tg_user_order_messages table

Revision ID: 210f59348ece
Revises: 34b0a6211581
Create Date: 2025-03-15 13:54:12.071874

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "210f59348ece"
down_revision: Union[str, None] = "34b0a6211581"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tg_user_order_messages",
        sa.Column(
            "approve", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "tg_user_order_messages",
        sa.Column("tg_id_approve", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tg_user_order_messages", "tg_id_approve")
    op.drop_column("tg_user_order_messages", "approve")
    # ### end Alembic commands ###
