"""added is_active in marzban_services table

Revision ID: c4e376b77f0a
Revises: 210f59348ece
Create Date: 2025-03-29 12:28:16.875213

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c4e376b77f0a"
down_revision: Union[str, None] = "210f59348ece"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "marzban_services",
        sa.Column(
            "is_active", sa.Boolean(), server_default="true", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("marzban_services", "is_active")
    # ### end Alembic commands ###
