"""delete ft coutry to tariff

Revision ID: f9933f4fee10
Revises: 904587f57543
Create Date: 2025-02-22 13:06:49.904508

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f9933f4fee10"
down_revision: Union[str, None] = "904587f57543"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "tariffs_country_id_fkey", "tariffs", type_="foreignkey"
    )
    op.drop_column("tariffs", "country_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tariffs",
        sa.Column(
            "country_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "tariffs_country_id_fkey",
        "tariffs",
        "countries",
        ["country_id"],
        ["id"],
    )
    # ### end Alembic commands ###
