"""remove tariff_key field from tariff table

Revision ID: 251dbaf72123
Revises: 85dc8439c979
Create Date: 2025-02-22 13:14:57.899348

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "251dbaf72123"
down_revision: Union[str, None] = "85dc8439c979"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tariffs",
        sa.Column(
            "is_archive",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="в архиве",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tariffs", "is_archive")
    # ### end Alembic commands ###
