"""extend StatusVirtualNetwork

Revision ID: 835f48f1563f
Revises: 4eb5bb6b907d
Create Date: 2025-03-08 13:00:59.179997

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "835f48f1563f"
down_revision: Union[str, None] = "4eb5bb6b907d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

status_user_virtual_networks_enum = postgresql.ENUM(
    "active", "inactive", "expired", "limited", name="status_user_virtual_networks"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    status_user_virtual_networks_enum.create(op.get_bind(), checkfirst=False)
    op.add_column(
        "user_virtual_networks",
        sa.Column(
            "status",
            status_user_virtual_networks_enum,
            nullable=True,
            comment="Состояние купленного виртуальной сети",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_virtual_networks", "status")
    status_user_virtual_networks_enum.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
