"""remove tariff_key field from tariff table

Revision ID: 85dc8439c979
Revises: 49706e681c71
Create Date: 2025-02-22 13:11:08.402963

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "85dc8439c979"
down_revision: Union[str, None] = "49706e681c71"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tariffs_tariff_key_key", "tariffs", type_="unique")
    op.drop_column("tariffs", "tariff_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tariffs",
        sa.Column(
            "tariff_key",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
            comment="Ключ для тарифа",
        ),
    )
    op.create_unique_constraint(
        "tariffs_tariff_key_key", "tariffs", ["tariff_key"]
    )
    # ### end Alembic commands ###
