"""add marzban_services table

Revision ID: c10fe6992553
Revises: 251dbaf72123
Create Date: 2025-03-08 00:51:19.717753

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c10fe6992553"
down_revision: Union[str, None] = "251dbaf72123"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "marzban_services",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("count_users", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "user_virtual_networks",
        sa.Column("marzban_service_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        "fk_marzban_services_user_virtual_networks",
        "user_virtual_networks",
        "marzban_services",
        ["marzban_service_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_marzban_services_user_virtual_networks",
        "user_virtual_networks",
        type_="foreignkey",
    )
    op.drop_column("user_virtual_networks", "marzban_service_id")
    op.drop_table("marzban_services")
    # ### end Alembic commands ###
