"""add orders, user_virtual_networks, tariffs, countries tables

Revision ID: 4f7ee076b8fb
Revises: f940dde41d8d
Create Date: 2025-01-09 00:04:47.570586

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4f7ee076b8fb"
down_revision: Union[str, None] = "f940dde41d8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "countries",
        sa.Column("view_country", sa.String(length=255), nullable=False),
        sa.Column("key_country", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_country"),
    )
    op.create_table(
        "tariffs",
        sa.Column("view_price", sa.String(length=255), nullable=False),
        sa.Column("term", sa.Integer(), nullable=False, comment="Количество времени"),
        sa.Column(
            "billing_period",
            sa.Enum("day", "month", "year", name="billing_period"),
            nullable=False,
            comment="Период времени",
        ),
        sa.Column("price", sa.Integer(), nullable=False, comment="Цена"),
        sa.Column(
            "currency",
            sa.Enum("dollars", "euro", "ruble", name="price_currency"),
            nullable=False,
            comment="Валюта",
        ),
        sa.Column(
            "tariff_key",
            sa.String(length=255),
            nullable=True,
            comment="Ключ для тарифа",
        ),
        sa.Column(
            "traffic_limit",
            sa.Integer(),
            server_default="200",
            nullable=False,
            comment="Объем разрешённого трафика",
        ),
        sa.Column("country_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="Статус тарифа"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["countries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tariff_key"),
    )
    op.create_table(
        "user_virtual_networks",
        sa.Column("virtual_network_key", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", name="status_user_virtual_networks"),
            nullable=False,
            comment="Состояние купленного виртуальной сети",
        ),
        sa.Column(
            "type_virtual_networks",
            sa.Enum(
                "vmess",
                "vless",
                "trojan",
                "shadowsocks",
                name="type_user_virtual_networks",
            ),
            nullable=False,
            comment="Тип виртуальной сети",
        ),
        sa.Column("virtual_networks", sa.Text(), nullable=False),
        sa.Column("expire", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "traffic_limit",
            sa.Integer(),
            server_default="200",
            nullable=False,
            comment="Объем разрешённого трафика",
        ),
        sa.Column(
            "tg_used_traffic",
            sa.Integer(),
            nullable=False,
            comment="Сколько гб пользователь уже израсходовал",
        ),
        sa.Column("tg_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "notified_low_traffic_data",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "notified_traffic_data_done",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "notified_expired_soon",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "notified_expired_done",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tg_user_id"],
            ["tg_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("virtual_network_key"),
    )
    op.create_table(
        "orders",
        sa.Column("virtual_network_key", sa.String(length=255), nullable=True),
        sa.Column("tariff_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False, comment="Сумма"),
        sa.Column("tg_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "currency",
            sa.Enum("dollars", "euro", "ruble", name="currency"),
            nullable=False,
            comment="Валюта",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "completed",
                "failed",
                "in_progress",
                "start",
                name="order_status",
            ),
            nullable=False,
            comment="Статус заказа",
        ),
        sa.Column(
            "type",
            sa.Enum("buy", "refill_traffic", "refill_traffic", name="order_type"),
            nullable=False,
            comment="Тип заказа",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tariff_id"],
            ["tariffs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tg_user_id"],
            ["tg_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders")
    op.drop_table("user_virtual_networks")
    op.drop_table("tariffs")
    op.drop_table("countries")
    # ### end Alembic commands ###
