"""add is_admin, is_admin_panel and is_active field in tg_users table

Revision ID: 33651d7488c6
Revises: dfe7edbc2eed
Create Date: 2025-03-15 13:01:25.892755

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "33651d7488c6"
down_revision: Union[str, None] = "dfe7edbc2eed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tg_users",
        sa.Column(
            "is_admin",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Является ли админом",
        ),
    )
    op.add_column(
        "tg_users",
        sa.Column(
            "is_admin_panel",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Может ли зайти в админ панель",
        ),
    )
    op.add_column(
        "tg_users",
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="Активен ли пользователь",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tg_users", "is_active")
    op.drop_column("tg_users", "is_admin_panel")
    op.drop_column("tg_users", "is_admin")
    # ### end Alembic commands ###
