"""change type traffic_limit, used_traffic fields in user_virtual_networks

Revision ID: dfe7edbc2eed
Revises: 835f48f1563f
Create Date: 2025-03-08 15:52:18.237382

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dfe7edbc2eed"
down_revision: Union[str, None] = "835f48f1563f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_virtual_networks",
        sa.Column(
            "used_traffic",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="Сколько гб пользователь уже израсходовал",
        ),
    )
    op.alter_column(
        "user_virtual_networks",
        "traffic_limit",
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(precision=10, scale=2),
        existing_comment="Объем разрешённого трафика",
        existing_nullable=False,
        existing_server_default=sa.text("200"),
    )
    op.drop_column("user_virtual_networks", "tg_used_traffic")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_virtual_networks",
        sa.Column(
            "tg_used_traffic",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Сколько гб пользователь уже израсходовал",
        ),
    )
    op.alter_column(
        "user_virtual_networks",
        "traffic_limit",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.INTEGER(),
        existing_comment="Объем разрешённого трафика",
        existing_nullable=False,
        existing_server_default=sa.text("200"),
    )
    op.drop_column("user_virtual_networks", "used_traffic")
    # ### end Alembic commands ###
